INSERT INTO states (name, uf) VALUES ('Acre', 'AC'),
                                     ('Alagoas', 'AL'),
                                     ('Amapá', 'AP'),
                                     ('Amazonas', 'AM'),
                                     ('Bahia', 'BA'),
                                     ('Ceará', 'CE'),
                                     ('Distrito Federal', 'DF'),
                                     ('Espírito Santo', 'ES'),
                                     ('Goiás', 'GO'),
                                     ('Maranhão', 'MA'),
                                     ('Mato Grosso', 'MT'),
                                     ('Mato Grosso do Sul', 'MS'),
                                     ('Minas Gerais', 'MG'),
                                     ('Pará', 'PA'),
                                     ('Paraíba', 'PB'),
                                     ('Paraná', 'PR'),
                                     ('Pernambuco', 'PE'),
                                     ('Piauí', 'PI'),
                                     ('Rio de Janeiro ', 'RJ'),
                                     ('Rio Grande do Norte ', 'RN'),
                                     ('Rio Grande do Sul', 'RS'),
                                     ('Rondônia', 'RO'),
                                     ('Roraima', 'RR'),
                                     ('Santa Catarina', 'SC'),
                                     ('São Paulo ', 'SP'),
                                     ('Sergipe', 'SE'),
                                     ('Tocantins', 'TO');

INSERT INTO cities (image, name, state_id) VALUES ('http://res.cloudinary.com/dgueb0wir/image/upload/v1620067165/cities/qba9nnjuklvusnmyptzj.png', 'Guarapuava', '16'),
                                                  ('http://res.cloudinary.com/dgueb0wir/image/upload/v1620067285/cities/ygoenr6qu5avjy8wykjc.jpg', 'Curitiba', '16');

INSERT INTO professions (name) VALUES ('Pedreiro'),
                                      ('Encanador'),
                                      ('Eletricista'),
                                      ('Pintor'),
                                      ('Jardineiro');